package:
  name: linux-headers
  version: 5.16.9
  epoch: 0
  description: "the Linux kernel headers (cross compilation)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - tar
      - xz
      - scanelf
      - ssl_client
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/kernel/v5.x/linux-${{package.version}}.tar.gz
      expected-sha256: ca84521580c9e2a5d7648a6b98150780b0e65bc8fac85c3a07d00b1b9aa68ad3
  - runs: |
      make mrproper
  - runs: |
      make headers
      find usr/include -name '.*' -delete
      rm usr/include/Makefile

      # Copy to cross-sysroot
      mkdir -p ${{targets.destdir}}/usr/include
      cp -rv usr/include/* ${{targets.destdir}}/usr/include/
