package:
  name: mpc
  version: 1.2.1
  epoch: 0
  description: "multiple-precision C library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-616adfeb.rsa.pub
      - https://packages.wolfi.dev/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - ca-certificates-bundle
      - debian-stage1
      - cross-gmp
      - cross-mpfr

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/mpc/mpc-${{package.version}}.tar.gz
      expected-sha256: 17503d2c395dfcf106b622dc142683c1199431d095367c6aacba6eec30340459
  - runs: |
      EGREP=egrep ./configure \
        --host=riscv64-linux-gnu \
        --target=riscv64-linux-gnu \
        --with-sysroot=/usr/riscv64-linux-gnu \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install

subpackages:
  - name: "cross-mpc"
    pipeline:
      - runs: |
          make install DESTDIR="${{targets.subpkgdir}}/usr/riscv64-linux-gnu"
    options:
      no-provides: true
      no-depends: true
      no-commands: true
