package:
  name: binutils
  version: 2.39
  epoch: 1
  description: "GNU binutils"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - isl
      - texinfo
      - zlib

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/binutils/binutils-${{package.version}}.tar.gz
      expected-sha256: d12ea6f239f1ffe3533ea11ad6e224ffcb89eb5d01bbea589e9158780fa11f10
  - name: 'Configure binutils'
    runs: |
      AR=ar ./configure \
        --prefix=/usr \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --disable-nls \
        --disable-werror \
        --disable-multilib \
        --disable-gprofng \
        --with-system-zlib
  - runs: |
      make -j$(nproc) V=1 AR=ar
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
