package:
  name: build-base
  version: 1
  epoch: 2
  description: "virtual package for builds"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - wolfi-baselayout
      - binutils
      - gcc
      - pkgconf
      - make

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
