package:
  name: flex
  version: 2.6.4
  epoch: 0
  description: "tool for generating text-scanning programs"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: BSD-2-Clause AND LGPL-2.0-or-later
  dependencies:
    runtime:
      - m4

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - bison

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/westes/flex/releases/download/v${{package.version}}/flex-${{package.version}}.tar.gz
      expected-sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995
  - name: 'Configure flex'
    runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}}
  - runs: |
      make -j$(nproc) V=1
  - uses: autoconf/make-install
  - runs: |
      ln -s flex ${{target.destdir}}/usr/bin/lex
  - uses: strip
