package:
  name: gmp
  version: 6.2.1
  epoch: 2
  description: "a library for arbitrary precision arithmetic"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later OR GPL-2.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - m4
      - texinfo

pipeline:
  - uses: fetch
    with:
      uri: https://gmplib.org/download/gmp/gmp-${{package.version}}.tar.xz
      expected-sha256: fd4829912cddd12f84181c3451cc752be224643e87fac497b69edddadc49b4f2
  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --enable-cxx \
        --with-pic
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
