package:
  name: libffi
  version: 3.4.2
  epoch: 0
  description: "portable foreign function interface library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - texinfo

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/libffi/libffi/releases/download/v${{package.version}}/libffi-${{package.version}}.tar.gz
      expected-sha256: 540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share \
         --enable-portable-binary \
         --enable-pax_emutramp \
         --disable-exec-static-tramp
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
