package:
  name: libxcrypt
  version: 4.4.36
  epoch: 0
  description: "Modern library for one-way hashing of passwords"
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext
      - libtool
      - pkgconf
      - wolfi-baselayout

pipeline:
  # Using Fetch instead of git checkout
  # @kaniini : When we retire libcrypt from glibc, it will need to get built earlier than git, as git (indirectly) depends on libcrypt.
  - uses: fetch
    with:
      uri: https://github.com/besser82/libxcrypt/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: b979838d5f1f238869d467484793b72b8bca64c4eae696fdbba0a9e0b6c28453

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --disable-static \
        --enable-hashes=strong,glibc \
        --enable-obsolete-api=no \
        --disable-failure-tokens

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxcrypt-doc
    pipeline:
      - uses: split/manpages
    description: libxcrypt manpages

  - name: libxcrypt-dev
    pipeline:
      - uses: split/dev
    description: libxcrypt dev

update:
  enabled: true
  release-monitor:
    identifier: 16436