package:
  name: mpc
  version: 1.2.1
  epoch: 1
  description: "multiple-precision C library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - gmp
      - mpfr

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/mpc/mpc-${{package.version}}.tar.gz
      expected-sha256: 17503d2c395dfcf106b622dc142683c1199431d095367c6aacba6eec30340459
  - runs: |
      EGREP=egrep ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
