package:
  name: mpfr
  version: 4.1.0
  epoch: 2
  description: "multiple-precision floating-point library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - texinfo
      - gmp

pipeline:
  - uses: fetch
    with:
      uri: https://www.mpfr.org/mpfr-${{package.version}}/mpfr-${{package.version}}.tar.xz
      expected-sha256: 0c98a3f1732ff6ca4ea690552079da9c597872d30e96ec28414ee23c95558a7f
  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
