package:
  name: patch
  version: 2.7.6
  epoch: 1
  description: "GNU patch"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/patch/patch-${{package.version}}.tar.gz
      expected-sha256: 8cf86e00ad3aaa6d26aca30640e86b0e3e1f395ed99f189b06d4c9f74bc58a4e
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
