package:
  name: pax-utils
  version: 1.3.4
  epoch: 1
  description: "ELF related utilities for 32-bit and 64-bit binaries"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-2.0-only
  dependencies:
    runtime:
      - scanelf

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - xz

pipeline:
  - uses: fetch
    with:
      uri: https://dev.gentoo.org/~xen0n/distfiles/pax-utils-${{package.version}}.tar.xz
      expected-sha256: 8baed2f9c5ae8e0cda1b9c75990864101afc64fad0a4616e10f3ff8ef891040b
  - runs: |
      make -j$(nproc) USE_CAP=no CC="${{host.triplet.gnu}}-gcc"
  - uses: autoconf/make-install
  - runs: |
      rm -f "${{targets.destdir}}"/usr/bin/lddtree

subpackages:
  - name: "scanelf"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/scanelf "${{targets.subpkgdir}}"/usr/bin/scanelf
