package:
  name: perl
  version: 5.36.0
  epoch: 0
  description: "Larry Wall's Practical Extraction and Report Language"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Artistic-Perl OR GPL-1.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - bison
      - zlib
      - bzip2

pipeline:
  - uses: fetch
    with:
      uri: https://www.cpan.org/src/5.0/perl-${{package.version}}.tar.gz
      expected-sha256: e26085af8ac396f62add8a533c3a0ea8c8497d836f0689347ac5abd7b7a4e00a

  # Delete bundled zlib and bzip2 sources
  - runs: |
      rm -rf cpan/Compress-Raw-Zlib/zlib-src
      rm -rf cpan/Compress-Raw-Bzip2/bzip2-src
      sed -i '/\(bzip2\|zlib\)-src/d' MANIFEST

  - name: 'Configure perl'
    runs: |
      BUILD_ZLIB=0
      BUILD_BZIP2=0
      BZIP2_LIB=/usr/lib
      BZIP2_INCLUDE=/usr/include

      export BUILD_ZLIB BUILD_BZIP2 BZIP2_LIB BZIP2_INCLUDE

      ./Configure -des \
         -Dcc=gcc \
         -Dcccdlflags='-fPIC' \
         -Dcccdlflags='-fPIC' \
         -Dccdlflags='-rdynamic' \
         -Dprefix=/usr \
         -Dprivlib=/usr/share/perl5/core_perl \
         -Darchlib=/usr/lib/perl5/core_perl \
         -Dvendorprefix=/usr \
         -Dvendorlib=/usr/share/perl5/vendor_perl \
         -Dvendorarch=/usr/lib/perl5/vendor_perl \
         -Dsiteprefix=/usr/local \
         -Dsitelib=/usr/local/share/perl5/site_perl \
         -Dsitearch=/usr/local/lib/perl5/site_perl \
         -Dlocincpth=' ' \
         -Duselargefiles \
         -Dusethreads \
         -Duseshrplib \
         -Dd_semctl_semun \
         -Dman1dir=/usr/share/man/man1 \
         -Dman3dir=/usr/share/man/man3 \
         -Dinstallman1dir=/usr/share/man/man1 \
         -Dinstallman3dir=/usr/share/man/man3 \
         -Dman1ext='1' \
         -Dman3ext='3pm' \
         -Dcf_by='Wolfi GNU/Linux' \
         -Ud_csh

      make -j$(nproc) libperl.so
      make -j$(nproc)

  - uses: autoconf/make-install

  - runs: |
      find "${{targets.destdir}}" -name '.*' -delete

  - uses: strip
