package:
  name: readline
  version: 8.1.2
  epoch: 0
  description: "GNU readline library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - ncurses

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz
      expected-sha256: f8ceb4ee131e3232226a17f51b164afc46cd0b9e6cef344be87c65962cb82b02
  - uses: patch
    with:
      patches: readline81-001.patch
      strip-components: 0
  - uses: patch
    with:
      patches: readline81-002.patch
      strip-components: 0
  - uses: patch
    with:
      patches: fix-ncurses-underlinking.patch
      strip-components: 0
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
