package:
  name: scdoc
  version: 1.11.2
  epoch: 0
  description: "simple man page generator written for POSIX systems with C99"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://git.sr.ht/~sircmpwn/scdoc/archive/${{package.version}}.tar.gz
      expected-sha256: e9ff9981b5854301789a6778ee64ef1f6d1e5f4829a9dd3e58a9a63eacc2e6f0
  - uses: autoconf/make
  - runs: |
      make install DESTDIR="${{targets.destdir}}" PREFIX="/usr"
  - uses: strip
