package:
  name: sqlite
  version: 3.39.2
  epoch: 0
  description: "C library which implements an SQL database engine"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: blessing
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - readline

pipeline:
  - uses: fetch
    with:
      uri: https://www.sqlite.org/2022/sqlite-autoconf-3390200.tar.gz
      expected-sha256: 852be8a6183a17ba47cee0bbff7400b7aa5affd283bf3beefc34fcd088a239de
  - name: Configure
    runs: |
      _amalgamation="-DSQLITE_ENABLE_FTS4 \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS \
        -DSQLITE_ENABLE_FTS3 \
        -DSQLITE_ENABLE_FTS5 \
        -DSQLITE_ENABLE_COLUMN_METADATA \
        -DSQLITE_SECURE_DELETE \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY \
        -DSQLITE_ENABLE_RTREE \
        -DSQLITE_ENABLE_GEOPOLY \
        -DSQLITE_USE_URI \
        -DSQLITE_ENABLE_DBSTAT_VTAB \
        -DSQLITE_MAX_VARIABLE_NUMBER=250000"
      export CFLAGS="$CFLAGS $_amalgamation"

      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-threadsafe \
         --enable-readline \
         --enable-static \
         --enable-dynamic-extensions \
         --enable-fts3

      sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
      sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool

      make -j$(nproc) V=1
  - uses: autoconf/make-install
  - uses: strip
