package:
  name: wolfi-base
  version: 1
  epoch: 0
  description: "Wolfi base metapackage"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - apk-tools
      - busybox
      - wolfi-keys

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
