package:
  name: wolfi-baselayout
  version: 1
  epoch: 2
  description: "baselayout data for stage3"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox

pipeline:
  - name: Generate /etc/shadow
    runs: |
      awk -F: '{
          pw = ":!:"
          if ($1 == "root") { pw = "::" }
          print($1 pw ":0:::::")
      }' vendor/etc/passwd > vendor/etc/shadow
  - name: Install
    runs: |
      for i in bin etc etc/profile.d home lib root var usr/bin usr/sbin usr/local tmp var/spool/cron; do
        mkdir -p "${{targets.destdir}}"/${i}
      done

      for i in lib64 usr/lib64 usr/local/lib64; do
        ln -s lib "${{targets.destdir}}"/${i}
      done

      for i in etc/passwd etc/group etc/shadow etc/services etc/hosts etc/profile etc/shells etc/protocols etc/inittab etc/profile.d/locale.sh; do
        install -m644 vendor/${i} "${{targets.destdir}}"/${i}
      done

      install -m600 vendor/etc/shadow "${{targets.destdir}}"/etc/shadow

      ln -s /etc/crontabs "${{targets.destdir}}"/var/spool/cron/crontabs
      ln -s /proc/mounts "${{targets.destdir}}"/etc/mtab
      ln -s /var/mail "${{targets.destdir}}"/var/spool/mail
