package:
  name: wolfi-keys
  version: 1
  epoch: 0
  description: "Wolfi signing keyring"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage2
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage2/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/etc/apk/keys
      install -m644 wolfi-signing.rsa.pub "${{targets.destdir}}"/etc/apk/keys
