package:
  name: cross-gcc-stage1
  version: 13.2.0
  epoch: 0
  description: "the GNU compiler collection (cross compilation)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - texinfo
      - gmp-dev
      - mpfr-dev
      - mpc1-dev
      - isl-dev
      - zlib-dev
      - gawk
      - bison
      - flex
      - cross-binutils-stage1

pipeline:
  - uses: fetch
    with:
      uri: https://gcc.gnu.org/pub/gcc/releases/gcc-${{package.version}}/gcc-${{package.version}}.tar.gz
      expected-sha256: 8cb4be3796651976f94b9356fa08d833524f62420d6292c5033a9a26af315078
  - name: 'Set up build directory'
    runs: |
      mkdir build
  - name: 'Configure GCC'
    runs: |
      cd build
      ../configure \
        --target=${{cross.triplet.gnu.glibc}} \
        --prefix=/usr \
        --disable-nls \
        --disable-werror \
        --with-glibc-version=2.35 \
        --with-newlib \
        --with-sysroot=/usr/${{cross.triplet.gnu.glibc}} \
        --without-headers \
        --enable-initfini-array \
        --disable-nls \
        --disable-shared \
        --disable-multilib \
        --disable-libcc1 \
        --disable-decimal-float \
        --disable-threads \
        --disable-libatomic \
        --disable-libgomp \
        --disable-libquadmath \
        --disable-libssp \
        --disable-libvtv \
        --disable-libstdcxx \
        --enable-languages=c,c++
  - runs: |
      make -C build -j$(nproc)
  - runs: |
      make -C build -j$(nproc) install DESTDIR="${{targets.destdir}}"
  - name: 'Clean up host aliases'
    runs: |
      rm -rf ${{targets.destdir}}/usr/${{cross.triplet.gnu.glibc}}
  - name: 'Fix limits.h'
    runs: |
      FULLPATH=${{targets.destdir}}/usr/lib/gcc/${{cross.triplet.gnu.glibc}}/${{package.version}}

      cat gcc/limitx.h gcc/glimits.h gcc/limity.h > $FULLPATH/include-fixed/limits.h
      cat gcc/gsyslimits.h > $FULLPATH/include-fixed/syslimits.h
  - name: 'Move fixed includes into main directory'
    runs: |
      FULLPATH=${{targets.destdir}}/usr/lib/gcc/${{cross.triplet.gnu.glibc}}/${{package.version}}

      mv $FULLPATH/include-fixed/syslimits.h $FULLPATH/include/syslimits.h
      mv $FULLPATH/include-fixed/limits.h $FULLPATH/include/limits.h
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
